name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: Java kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter proje oluştur
        run: |
          flutter create .
          flutter pub get

      - name: APK üret
        run: flutter build apk --release

      - name: APK yükle
        uses: actions/upload-artifact@v4
        with:
          name: babil-apk
          path: build/app/outputs/flutter-apk/app-release.apk
